/** The code is written in a way to make varying numbers of categories
 *  and questions possible by changing these constants.
 * 
 *  However, increasing the number of questions above 5 drastically limits
 *  performance. Most of the API-provided categories only have 5 unique clues,
 *  and randomly requesting categories until the board is filled will take 
 *  more and more time as NUM_QUESTIONS increases.
 */
const NUM_CATEGORIES = 6;
const NUM_QUESTIONS_PER_CAT = 5;

/** From testing with the jService API, category IDs start at 1 and
 *  end at 18418.
 */
const NUM_API_CATEGORIES = 18418;
const categoryIDSet = new Set();

// From testing with the jService API, clue values cap at 1000

const NUM_MAX_CLUE_VALUE = 1000;

let categories = [];

/** Given a set of category IDs, return the array of categories
 *  once the promises all resolve.
 */
function getCategoriesFromIDSet(categoryIDSet) {
  let categoryArray = [];
  categoryIDSet.forEach((id) => {
    categoryArray.push(getCategory(id));
  });
  return Promise.all(categoryArray);
}

/** Given a category ID, return the Promise of a category from the jservice
 *  API, then convert it into an object. If the request fails, return a
 *  predefined object instead that will be later filtered out of the
 *  valid categories.
 */
function getCategory(categoryID) {
  return fetch(`https://jservice.io/api/category?id=${categoryID}`)
    .then((response) => response.json())
    .catch(() => {
      return { category: "", id: -1, clues: [] };
    });
}

/** Given a number of IDs to get and the maximum ID number value allowed,
 *  generate random ID numbers and check them against the global
 *  categoryIDSet variable before adding them to a set to return.
 *  This ensure the IDs are unique both within the set and the categories
 *  being used thus far.
 */
function getRandomIDSet(numIDs, maxValue) {
  let uniqueIDSet = new Set();
  while (uniqueIDSet.size < numIDs) {
    let randomID = 1 + Math.floor(Math.random() * maxValue);
    if (!categoryIDSet.has(randomID)) {
      uniqueIDSet.add(randomID);
    }
  }
  return uniqueIDSet;
}

/** Given a category object, filter its clues array to eliminate empty or
 *  invalid clues, then construct a set of unique clues to avoid adding
 *  duplicates within a category. These steps are necessary because the
 *  jservice API can return clues with duplicate, empty, and/or invalid
 *  questions, but the clues will still have unique clue IDs.
 */
function getUniqueClues(category) {
  let validClueArray = category.clues.filter((clue) => {
    return clue.question !== "" && clue.invalid_count === null;
  });
  let uniqueClueQuestionSet = new Set();
  let uniqueClueIDSet = new Set();
  validClueArray.forEach((clue) => {
    if (!uniqueClueQuestionSet.has(clue.question)) {
      uniqueClueQuestionSet.add(clue.question);
      uniqueClueIDSet.add(clue.id);
    }
  });
  return validClueArray.filter((clue) => uniqueClueIDSet.has(clue.id));
}

/** Given an array of clues, generate a map that holds the clues in arrays.
 *  The map keys are generated by comparing the clue's value to the incremental
 *  increase in prize value as the difficulty increases.
 *  By using Number(clue.value), null values become added to the '0' key's array.
 *
 *  Ultimately, the map contains keys (0-n) for each quotient of the clue difficulty
 *  value, with arrays of the clues at each difficulty.
 */
function sortClueDifficulty(clueArray) {
  let difficultyIncreaseValue = NUM_MAX_CLUE_VALUE / NUM_QUESTIONS_PER_CAT;
  let clueMap = new Map();
  clueArray.forEach((clue) => {
    let index = Math.round(Number(clue.value) / difficultyIncreaseValue);
    if (!clueMap.has(index)) {
      clueMap.set(index, []);
    }
    clueMap.get(index).push(clue);
  });
  return clueMap;
}

/** Given an index and a sorted Map of clues, iterate through the Map to find the
 *  closest key-value pair at or below the index (where index is used as a key).
 *  Because the returned array will be spliced and shrunk, if it has only 1 element
 *  the array is deleted from the map before the clue array is returned.
 */
function hardestCluesFromIndex(index, sortedClueMap) {
  let counter = index;
  while (!sortedClueMap.has(counter) && counter > 0) {
    counter--;
  }
  let cluesFromIndex = sortedClueMap.get(counter);
  if (cluesFromIndex.length === 1) {
    sortedClueMap.delete(counter);
  }
  return cluesFromIndex;
}

/** Given an index and a sorted Map of clues, identify the array of the most difficult
 *  clues that can be used for the given index. Then choose a random clue from this array
 *  and remove it before returning the removed clue.
 *
 *  Ultimately, the process of sorting clues by difficulty and choosing a random clue at
 *  each difficulty means that even if a category is seen in multiple games, there is no
 *  guarantee that players will see repeat clues - as long as the category has enough clues
 *  to support the variation.
 */
function getRandomClueFromIndex(index, sortedClueMap) {
  let cluesFromIndex = hardestCluesFromIndex(index, sortedClueMap);
  let randomClueIndex = Math.floor(Math.random() * cluesFromIndex.length);
  return cluesFromIndex.splice(randomClueIndex, 1)[0];
}

function buildClueArray(sortedClueMap) {
  let clueArray = Array.from({ length: NUM_QUESTIONS_PER_CAT });
  for (let x = 0; x < clueArray.length; x++) {
    clueArray[x] = getRandomClueFromIndex(x + 1, sortedClueMap);
  }
  return clueArray;
}

/** Given an array of category objects, iterate through the array to obtain categories
 *  with enough unique, usable clues to satisfy the number of clues required.
 *
 *  Note - this may return a smaller number of categories that is included in the
 *  original array, meaning additional categories will be needed to complete the game
 *  board.
 */
function filterCategories(categoryArray, numClues) {
  let filteredCategories = [];
  categoryArray.forEach((category) => {
    let uniqueClues = getUniqueClues(category);
    if (uniqueClues.length >= numClues) {
      let clues = buildClueArray(sortClueDifficulty(uniqueClues));
      categoryIDSet.add(category.id);
      let uniqueCategory = { title: category.title, clues };
      filteredCategories.push(shortenCategory(uniqueCategory));
    }
  });
  return filteredCategories;
}

/* This function edits the data in a given category to match the format requested by
 *  Springboard.
 */
function shortenCategory(categoryObj) {
  let { title, clues } = categoryObj;
  let shortenedClues = [];
  for (let clue of clues) {
    let { question, answer, value } = clue;
    shortenedClues.push({
      question: removeHTML(question),
      answer: removeHTML(answer),
      value,
      showing: null,
    });
  }
  return { title: removeHTML(title), clues: shortenedClues };
}

function removeHTML(htmlString) {
  let parser = new DOMParser();
  return parser
    .parseFromString(htmlString, "text/html")
    .body.textContent.toUpperCase()
    .replace("\\'", "'");
}

/** Await is used here because the category data is required before the categories
 *  can be filtered (based on duplicates usable clues).
 */
async function getValidCategories(amountCategories) {
  let idSet = getRandomIDSet(amountCategories, NUM_API_CATEGORIES);
  let categoriesFromID = await getCategoriesFromIDSet(idSet);
  return filterCategories(categoriesFromID, NUM_QUESTIONS_PER_CAT);
}

/** Await is used here because the information on the filtered categories is required
 *  before determining whether the array has enough valid categories to complete the
 *  game board.
 */
async function fillArrayWithValidCategories() {
  let amountCategories = NUM_CATEGORIES;
  categories = await getValidCategories(amountCategories);
  while (categories.length < NUM_CATEGORIES) {
    let missingCategoryNum = NUM_CATEGORIES - categories.length;
    categories = categories.concat(
      await getValidCategories(missingCategoryNum)
    );
  }
}

/** Fill the HTML table#jeopardy with the categories & cells for questions.
 *
 * - The <thead> should be filled w/a <tr>, and a <td> for each category
 * - The <tbody> should be filled w/NUM_QUESTIONS_PER_CAT <tr>s,
 *   each with a question for each category in a <td>
 *   (initally, just show a "?" where the question/answer would go.)
 * 
 *  Edited to display clue values instead of "?"
 */
async function fillTable() {
  const $table = $("#jeopardy");
  const $tableHead = $("<thead><tr>");
  const $tableBody = $("<tbody>");
  for (let category of categories) {
    $tableHead
      .find("tr")
      .append($(`<td class="category-title">${category.title}</td>`));
  }
  for (let x = 0; x < NUM_QUESTIONS_PER_CAT; x++) {
    const $questionRow = $("<tr>");
    let displayValue = (NUM_MAX_CLUE_VALUE / NUM_QUESTIONS_PER_CAT) * (x + 1);
    displayValue = Math.round(displayValue / 50) * 50;
    for (let y = 0; y < NUM_CATEGORIES; y++) {
      const $clue = $(`<td class="clue">$${displayValue}</td>`);
      $clue.addClass("unclicked").data({ categoryIndex: y, clueIndex: x });
      $questionRow.append($clue);
    }
    $tableBody.append($questionRow);
  }
  $table.append($tableHead);
  $table.append($tableBody);
}

/** Handle clicking on a clue: show the question or answer.
 *
 * Uses .showing property on clue to determine what to show:
 * - if currently null, show question & set .showing to "question"
 * - if currently "question", show answer & set .showing to "answer"
 * - if currently "answer", ignore click
 * 
 *  Edited to set showing to "flipQandA" - as the card will flip between
 *  question and answer on click, so distinguishing between them is no
 *  longer needed.
 * */
function handleClick(evt) {
  const $clue = $(evt.target).closest(".clue");
  let { categoryIndex, clueIndex } = $clue.data();
  let clueInfo = categories[categoryIndex].clues[clueIndex];
  if (clueInfo.showing === null) {
    clueInfo.showing = "flipQandA";
    $clue.addClass("shrink");
    $clue.on("animationiteration", () => {
      $clue.removeClass("unclicked").addClass("clue-q-and-a").text("");
      addFaces($clue, clueInfo);
    });
    $clue.on("animationend", () => {
      $clue.removeClass(["shrink"]);
    });
    return;
  } else if (clueInfo.showing === "flipQandA") {
    $clue.toggleClass("flip");
    return;
  }
}

function addFaces($clue, clueInfo) {
  let $faceFront = $('<div class="face">');
  $faceFront.text(clueInfo.question);
  let $faceBack = $('<div class="face">');
  $faceBack.text(clueInfo.answer);
  $clue.append([$faceFront, $faceBack]);
}

/** Wipe the current Jeopardy board, show the loading spinner
 */
function showLoadingView() {
  $("#jeopardy").fadeOut(100);
  $("#button-container").fadeOut(100, () => {
    $("#jeopardy").empty();
    $(".loading").show();
  });
}

/** Remove the loading spinner and display the game board. */

function hideLoadingView() {
  $("#jeopardy").fadeIn(100);
  $("#button-container").fadeIn(100);
  $(".loading").hide();
}

/** Start game:
 *
 * - get random category Ids
 * - get data for each category
 * - create HTML table
 * */

/** Note - normally, I would create the buttons in the HTML file instead of
 *  in the JS code, however the given instructions state:
 *    "We’ve provided an HTML file and CSS for the application
 *     (you shouldn’t change the HTML file; if you want to tweak
 *     any CSS things, feel free to)."
 *  While the help page ultimately was coded into the HTML file, I opted to 
 *  respect this rule in all other circumstances.
 */
async function setupAndStart() {
  const $loadingCircle = $(`<div class="loading">`).hide();
  $("body").append($loadingCircle);
  $("#start").on("click", hideHelp);
  await fillArrayWithValidCategories().then(function () {
    const $gameTable = $('<table id="jeopardy">').hide();
    const $buttonHolder = $('<div id="button-container">');
    const $restartButton = $('<button id="restart">Restart</button>');
    $restartButton.addClass("color-button").on("click", restart);
    const $helpButton = $('<button id="help-button">help</button>');
    $helpButton
      .addClass(["color-button", "material-symbols-outlined"])
      .on("click", showHelp);
    $buttonHolder.append([$restartButton, $helpButton]).hide();
    $("body").append([$gameTable, $buttonHolder]);
    fillTable();
  });
}

/** On click of start / restart button, set up game. */

async function restart() {
  showLoadingView();
  categoryIDSet.clear();
  await fillArrayWithValidCategories().then(function () {
    fillTable();
    hideLoadingView();
  });
}

/** These functions act to swap between the current board and the help page.
 */
function hideHelp() {
  $("#help").slideToggle(300, () => {
    $("#jeopardy").fadeIn(150);
    $("#button-container").fadeTo(150, 1);
  });
}

function showHelp() {
  $("#jeopardy").fadeOut(150);
  $("#button-container").fadeTo(150, 0, () => {
    $("#help").slideToggle(300);
  });
}

/** On page load, add event handler for clicking clues */

/** Note - this could have been done using a listener for the "load" or
 * "DOMContentLoaded" events to trigger adding the event handler. I opted
 *  to use event delegation instead, as it means only one event handler is
 *  needed, rather than adding one handler to trigger adding another.
 */
$("body").on("click", ".clue", handleClick);

setupAndStart();